### ISSUE TITLE
How to let the bot manage channel name and icon?

### ISSUE THREAD

**Issue by tebjan** [t2bot/t2bot.io#38]
I tried to mirror a complete discord server on matrix, I started to bridge the channels by hand. but I noticed it is somehow also possible to let the bot handle that:

![image](https://user-images.githubusercontent.com/1094716/81567844-31a0ed00-939d-11ea-816c-a6c7cf5528c1.png)

the upper one is auto managed (I think I clicked on a channel link from a discord message), lower one created manually.

since the server name and logo have changed, some channels are automatically updated, but the ones I did create manually are not. is there an easy way to update the other channels as well, it's quite a few...

another solution would also be to mirror all channels again in a new community. is there any command to generate all channels of a discord server at once?

**Comment by turt2live** [comment]
Please use #help:t2bot.io for support. The bridge wants higher permissions in Matrix.
