### ISSUE TITLE
Add support for Discord Announcement Channels

### ISSUE THREAD

**Issue by deepadmax** [t2bot/t2bot.io#56]
Currently, channels marked as Announcement Channel can't be bridged. You need to unmark it, bridge it, and mark it again. It works fine even if it's marked as such. It just can't be marked at the time of bridging. This is problematic if people are already following the channel, as it would break the follower's feed and remove the channel from their server.

**Comment by deepadmax** [comment]
I apologise for this issue here. I just noticed that this is the repository for the website. I meant this issue to be about what I now know is `matrix-appservice-discord`. However, there's no functionality to post issues in that repository; how would you recommend I pass this on?

**Comment by turt2live** [comment]
It should be reported to the upstream repo: https://github.com/Half-Shot/matrix-appservice-discord
