### ISSUE TITLE
discord to matrix gif issues

### ISSUE THREAD

**Issue by Gibbz** [t2bot/t2bot.io#63]
Not sure if this is the right spot for this bug.
The discord to matrix bridge has some issues bringing gifs from discord to matrix.
They come in as a link rather than an embedded animated gif.

Thanks for the great software btw!

**Comment by turt2live** [comment]
Please report issues in [#help:t2bot.io](https://matrix.to/#/#help:t2bot.io) so they aren't forgotten please.
